---
local_home: "{{ lookup('env', 'HOME') }}"
lisp_dir: "{{ local_home }}/.emacs.d/lisp"
dot_files: ['bashrc', 'gitignore', 'bash_paths', 'gitconfig', 'emacs', 'signature.txt']
matplotlib_path: "{{ local_home }}/.config/matplotlib"
ipython_path: "{{ local_home }}/.ipython/profile_default"
anaconda_path: "{{ local_home}}/anaconda"
git_path: "{{ local_home }}/git"
fipy_path: "{{ git_path }}/fipy"
role_path: "{{ git_path }}/env/roles/common"
config_paths:
  - "{{ matplotlib_path }}"
  - "{{ ipython_path }}"
  - "{{ ipython_path }}/static/custom"
  - "{{ ipython_path }}"
config_files:
  - 'matplotlibrc'
  - 'ipython_config.py'
  - 'custom.js'
  - 'ipython_notebook_config.py'
