---
 - name: check if anaconda is installed
   stat: path={{ anaconda_path }}
   register: anaconda_dir

 - name: get latest miniconda
   get_url: url=https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh dest=/tmp
   when: anaconda_dir.stat.exists == False

 - name: install miniconda
   shell: bash /tmp/Miniconda-latest-Linux-x86_64.sh -b -p {{ anaconda_path }}
   args:
     creates: "{{ anaconda_path }}"
   when: anaconda_dir.stat.exists == False

 - name: update conda
   shell: "{{ anaconda_path }}/bin/conda update conda"

 - name: install anaconda
   shell: "{{ anaconda_path }}/bin/conda install anaconda"

 - name: install new enviroment
   shell: "{{ anaconda_path }}/bin/conda env update -n root --file {{ role_path }}/files/environment.yml"

 - name: install javascript with conda
   shell: "{{ anaconda_path }}/bin/conda install -c https://conda.anaconda.org/javascript nodejs"
   tags: javascript
